version: '3'

services:
  db:
    image: library/postgres:alpine
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data